[tool.poetry]
name = "nqs-llm"
version = "0.0.0"
repository = "https://github.com/rdguez-mariano/portfolio"
description = "Nano Quant Services (NQS) LLM package"
authors = ["Mariano Rodriguez <rdguez.mariano@gmail.com>"]
readme = "README.md"
packages = [{include = "nqs", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9.8,<4.0"  # needed for streamlit
nqs-core = {path = "../core", develop = true}
fastapi = {version = "^0.111.0", extras = ["all"]}
protobuf = "*"
langchain = "^0.2.1"
langchain-community = "^0.2.1"
langgraph = "^0.0.62"
beautifulsoup4 = "^4.12.3"
lxml = "^5.2.2"
html2text = "^2024.2.26"
google-cloud-aiplatform = "^1.53.0"
langchain-google-vertexai = "^1.0.4"
google-cloud-speech = "^2.27.0"
langchain-huggingface = "^0.0.3"
bitsandbytes = "^0.43.1"
accelerate = "^0.30.1"
transformers = "^4.41.1"
sentencepiece = "^0.2.0"
sentence-transformers = "^3.0.0"
faiss-gpu = "^1.7.2"
langchain-mistralai = "^0.1.13"
pacmap = "^0.7.2"
plotly = "^5.22.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
nqs-dev = {path = "../dev", develop = true}
nqs-tests = {path = "../tests", develop = true}

[tool.black]
target-version = ['py39']
line_length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_local_folder = ["nqs"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
