[tool.poetry]
name = "nqs-app"
version = "0.0.0"
repository = "https://github.com/rdguez-mariano/portfolio"
description = "Nano Quant Services (NQS) App package"
authors = ["Mariano Rodriguez <rdguez.mariano@gmail.com>"]
readme = "README.md"
packages = [{include = "nqs", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9.8,<4.0"  # needed for streamlit
plotly = "^5.16.0"
XlsxWriter = "^3.1.2"
streamlit = "^1.25.0"
streamlit-javascript = "^0.1.5"
streamlit-authenticator = "^0.3.2"
altair = "^4.0"
flask = "^3.0.3"
fastapi = {version = "^0.111.0", extras = ["all"]}
gunicorn = "^22.0.0"
streamlit-js-eval = "^0.1.7"
millify = "^0.1.1"
nqs-llm = {path = "../llm", develop = true}

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
nqs-dev = {path = "../dev", develop = true}
nqs-tests = {path = "../tests", develop = true}

[tool.black]
target-version = ['py39']
line_length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_local_folder = ["nqs"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
