[tool.poetry]
name = "nqs-dev"
version = "0.0.0"
repository = "https://github.com/rdguez-mariano/portfolio"
description = "Nano Quant Services (NQS) Dev package"
authors = ["Mariano Rodriguez <rdguez.mariano@gmail.com>"]
packages = [{include = "nqs", from = "src"}]

[tool.poetry.dependencies]
vprof = "^0.38"
black = "24.4.2"
flake8 = "7.0.0"
isort = "5.13.2"
mypy = "1.10.0"
pre-commit = "3.7.1"
ipykernel = "*"
nbformat = "*"
ipywidgets = "*"
tqdm = "*"

[tool.black]
target-version = ['py39']
line_length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_local_folder = ["nqs"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
