[tool.poetry]
name = "nqs-core"
version = "0.0.0"
repository = "https://github.com/rdguez-mariano/portfolio"
description = "Nano Quant Services (NQS) Core package"
authors = ["Mariano Rodriguez <rdguez.mariano@gmail.com>"]
readme = "README.md"
packages = [{include = "nqs", from = "src"}]

[tool.poetry.dependencies]
future = "^0.18.2"
numpy = "^1.21.2"
tqdm = "^4.62.2"
pydantic = "*"  # for BaseModel
pandas = "*"

[tool.black]
target-version = ['py39']
line_length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_local_folder = ["nqs"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
